services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: code-server
    
    ports:
      - 8080:8080

    volumes:
      - .:/workspace

    environment:
      - PASSWORD=code4life 
      - VSCODE_PROXY_URI=./proxy/{{port}}
      - DISPLAY=:0
      - VNC_URL=

    labels:
      caddy: codeserver.do.jointheleague.org
      caddy.reverse_proxy: "{{upstreams 8080}}"

    networks:
      - x11
      - caddy

networks:
  x11:
    internal: true
  caddy:
    external: true
