services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: code-server
    
    ports:
      - "8080:8080"
      - "6080:6080"
      #- "5900:5900"

    #volumes:
    #  - /Users/eric/proj/league-projects/league-vscode-ext:/workspace

    environment:
      #- KST_REPORTING_URL=http://code-server/telem
      - KST_REPORTING_URL=http://192.168.1.49:5000/telem
      - KST_REPORT_RATE=30
      - WORKSPACE_FOLDER=/workspace/Python-Apprentice
      - VNC_URL=https://codespace.doswarm.jointheleague.org/vnc/
      - INITIAL_GIT_REPO=https://github.com/league-curriculum/Python-Apprentice
      - JTL_SYLLABUS=/workspace/Python-Apprentice/lessons/.jtl/syllabus-1h.yaml

    labels:
      caddy: codespace.doswarm.jointheleague.org

      # WebSocket handler for /websockify
      caddy.@ws.0_header: Connection *Upgrade*
      caddy.@ws.1_header: Upgrade websocket

      # Make websockify route first
      caddy.0_route.handle: /websockify*
      caddy.0_route.handle.reverse_proxy: "@ws {{upstreams 6080}}"
      # VNC route second
      caddy.1_route.handle: /vnc/*
      caddy.1_route.handle_path: /vnc/*
      caddy.1_route.handle_path.reverse_proxy: "{{upstreams 6080}}"
      # Catch-all route last
      caddy.2_route.handle: /*
      caddy.2_route.handle.reverse_proxy: "{{upstreams 8080}}"

      # Basic auth:
      #caddy.2_route.handle.basic_auth: admin
      caddy.basic_auth.admin: $$2a$$14$$dvvmGyTMamr5SONPH0vbweeD2Ng767yBIOCtr1.BQ17PK7sU/0C5W
      

    networks:
      - caddy

networks:
  x11:
    internal: true
  caddy:
    external: true
