services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: code-server
    
    ports:
      - 8080:8080

    #volumes:
    #  - /Users/eric/proj/league-projects/league-vscode-ext:/workspace

    environment:
      - PASSWORD=code4life 
      - VSCODE_PROXY_URI=./proxy/{{port}}
      - DISPLAY=novnc:0
      - VNC_URL=https://codeserver-vnc.do.jointheleague.org/
      - KST_REPORTING_URL=http://code-server/telem
      - KST_CONTAINER_ID=container-123
      - KST_REPORT_RATE=1
      - KST_DEBUG=1
      - WORKSPACE_FOLDER=/workspace/Python-Apprentice

    labels:
      caddy: codeserver.do.jointheleague.org
      caddy.reverse_proxy: "{{upstreams 8080}}"

    networks:
      - x11
      - caddy

  novnc:  

    image: ghcr.io/league-infrastructure/novnc-service:v0.1.3
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=600
      - DISPLAY_HEIGHT=600
      - RUN_XTERM=no

    ports:
      - 6080 
      - 5900
    
    labels:
      caddy: codeserver-vnc.do.jointheleague.org
      caddy.@ws.0_header: Connection *Upgrade*
      caddy.@ws.1_header: Upgrade websocket
      caddy.0_reverse_proxy: "@ws {{upstreams 6080}}"
      caddy.1_reverse_proxy: "{{upstreams 6080}}"

    networks:
      - x11
      - caddy 

networks:
  x11:
    internal: true
  caddy:
    external: true
